name: 'PR Comment'
description: 'Add a comment to a closed PR'

inputs:
  token:
    description: 'GITHUB_TOKEN or a repo scoped PAT.'
    default: ${{ github.token }}

outputs:
  time:
    description: 'When the action was run'
  comment-id:
    description: 'The id of the created comment'

runs:
  using: 'node12'
  main: 'index.js'